apiVersion:  apps/v1
kind:  Deployment
metadata:
  name: {{ .Values.deployment_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.pod_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod_label }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ trimAll "" .Values.image.tag }}
          name: {{ .Values.container_name }}
          ports:
          - containerPort: {{ .Values.containerport }}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
spec:
  type:  NodePort
  ports:
    -  port: {{ .Values.port }}
       targetPort: {{ .Values.targetport }}
       nodePort: {{ .Values.nodeport }}
       protocol: TCP
  selector:
    app:  {{ .Values.pod_label }}
