# This is a basic workflow to help you get started with Actions

name: replace variables and helm deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout the code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Run script
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          chmod +x ./.github/scripts/replace_var.sh
          ./.github/scripts/replace_var.sh
        shell: bash
      
      - name: Cat new file
        run: cat values-DEV.yaml.new
        
      - name: copy value-DEV file to helm
        run: |
           pwd
           ls -al
           cp -rf values-DEV.yaml.new ./mychart2/values.yaml
           ls -al mychart2/
      
      - name: debug dry run helm
        run: |
           pwd
           ls -al mychart2
           helm install nginx-release ./mychart2/ --debug --dry-run

      - name: deploy nginx to k8s
        run:
          helm install nginx-release ./mychart2/

      
