name: helm deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
   build:
     name: Setup, Build, Publish, and Deploy
     runs-on: self-hosted
     steps:
       - name: checkout the code
         uses: actions/checkout@v3
         
       - name: copy value-DEV file to helm
         run: |
           pwd
           ls -al
           cp -rf values-DEV.yaml.new ./mychart2/values.yaml
           ls -al mychart2/
       
       - name: debug dry run helm
         run:
           helm install nginx-release ./mychart2/ --debug --dry-run
          
          
